Vagrant.configure("2") do |config|
  config.vm.define 'master' do |master|
    master.vm.box = "hashicorp/bionic64"
    master.vm.network "forwarded_port", guest: 22, host: 2200
    master.vm.network "private_network", ip: "10.0.0.50"
    master.vm.host_name = "master"
  ## Use all the defaults:
    master.vm.provision :salt do |salt|

      salt.master_config = "salt/master"
      salt.minion_id = 'master' # Not used now but possibly I may add minion config to the master at some point
      salt.no_minion = true
      salt.install_master = true
      salt.run_highstate = false
    end
  end
  config.vm.define 'minion01' do |min01|
    min01.vm.box = "hashicorp/bionic64"
    min01.vm.network "forwarded_port", guest: 22, host: 2201
    min01.vm.network "private_network", ip: "10.0.0.51"
    min01.vm.host_name = "minion01"
  ## Use all the defaults:
    min01.vm.provision :salt do |salt|

      salt.masterless = false
      salt.minion_config = "salt/minion"
      salt.minion_id = 'minion01'
      salt.run_highstate = false
    end
  end
end
